---
- name: check 4.5+ build system is used
  fail:
    msg: "Only 4.5+ build system is supported"
  when: version.major < 4 or 
        (version.major == 4 and version.minor <= 4)

- name: check this is a patch release
  fail:
    msg: Only PATCH releases (X.Y.Z -> X.Y.(Z+1)) are supported
  when: version.major != prev_version.major or
        version.minor != prev_version.minor

- name: confirmation dialog
  pause:
    prompt: |

        === RELEASING {{ version.name }} ===
        Using git branch: {{ git_branch }}
        Previosuly released version: {{ prev_version.name }}
        
        To abort, press Ctrl+C A
