---
- name: create tarball
  shell: make dist
  args:
    chdir: "{{ git_repo_local }}"

- name: create gpg signature
  shell: gpg2 --batch --yes --armor --detach-sign freeipa-{{ version.name }}.tar.gz
  args:
    chdir: "{{ git_repo_local }}"

- name: verify gpg signature
  shell: gpg2 --verify freeipa-{{ version.name }}.tar.gz.asc
  args:
    chdir: "{{ git_repo_local }}"
  register: tarball_verify

- name: show tarball signature
  debug:
    var: tarball_verify.stdout_lines

- name: show tarball signature
  debug:
    var: tarball_verify.stderr_lines

- name: copy tarball and signature
  shell: "cp freeipa-{{ version.name }}.tar.gz* {{ artifacts_dest }}"
  args:
    chdir: "{{ git_repo_local }}"
